#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-key: xx
#      secret-key: xx
#      oss:
#        endpoint: oss-cn-shenzhen.aliyuncs.com
#        bucket: gulimall-20210904
#      sms:
#        host: https://fesms.market.alicloudapi.com
#        path: /sms/
#        sign: 1
#        skin: 1
#        appcode: d6b04aee2d8c4ef09f2eda5beff58ef3

#  application:
#    name: gulimall-third-party

#server:
#  port: 30000
